### ISSUE TITLE
Build with Yggdrasil

### ISSUE THREAD

**Issue by matbesancon** [Pangoraw/Polars.jl#4]
Cool project! One way to ease the Julia user installation would be to build the polar-rs library on https://github.com/JuliaPackaging/Yggdrasil, and then depend on the built library in this wrapper

**Comment by Pangoraw** [comment]
Thanks! There is already a PR to Yggdrasil (https://github.com/JuliaPackaging/Yggdrasil/pull/7230) so that Polars.jl can depend on libpolars_jll once merged.

**Comment by matbesancon** [comment]
I had missed it, closing this one then :)
