### ISSUE TITLE
Problems creating a dataframe

### ISSUE THREAD

**Issue by artemsolod** [Pangoraw/Polars.jl#5]
I have problems creating a `DataFrame` following the documentation notebook. Tried on MacOS and Ubuntu. The package was installed with `add https://github.com/Pangoraw/Polars.jl.git`

```
(@v1.9) pkg> activate .
(polarsjl) pkg> add https://github.com/Pangoraw/Polars.jl.git

julia> using Polars
julia> DataFrame((;quantity = [1,         2,          missing      ]))
ERROR: could not load symbol "polars_dataframe_new_from_carrow":
dlsym(0x9dd0a690, polars_dataframe_new_from_carrow): symbol not found
Stacktrace:
 [1] polars_dataframe_new_from_carrow
   @ ~/.julia/packages/Polars/kIHN5/src/API.jl:105 [inlined]
 [2] DataFrame(table::NamedTuple{(:quantity,), Tuple{Vector{Union{Missing, Int64}}}})
   @ Polars ~/.julia/packages/Polars/kIHN5/src/Polars.jl:68
 [3] top-level scope
   @ REPL[8]:1
```

**Comment by Pangoraw** [comment]
Hi! the libpolars_jll is currently not up to date with latest changes in the repo, so it currently need to be built manually, see [the Polars C-API](https://github.com/Pangoraw/Polars.jl?tab=readme-ov-file#polars-c-api) section. I will try to update it soon.

**Comment by artemsolod** [comment]
Thank you! Got it working after building the `libpolars.so` and manually copying it to `~/.julia/artifacts/`. Is this the intended way or I could have made it work without direct copying?

**Comment by Pangoraw** [comment]
Just building in debug mode (`cargo build`) and precompiling polars again should work. It should detect that the file `c-polars/target/debug/libpolars.so` exists and use it instead of the one in libpolars_jll:

https://github.com/Pangoraw/Polars.jl/blob/06326d10a2515f907d25fde942c21d7e34175df2/src/API.jl#L8-L11

**Comment by Pangoraw** [comment]
FYI, updating libpolars_jll to 0.1.1 should now give a compatible library (no need to build).
